# Generated by Django 3.2.5 on 2021-08-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210823_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=50, verbose_name='Task'),
        ),
    ]
